"""Profile builder — executes profile queries from trigger config to build a 360-degree customer profile."""

from __future__ import annotations

import logging

import asyncpg

from growthclaw.models.trigger import TriggerRule

logger = logging.getLogger("growthclaw.intelligence.profile_builder")


async def build_profile(
    conn: asyncpg.Connection,  # type: ignore[type-arg]
    user_id: str,
    trigger: TriggerRule,
) -> dict:
    """Execute the profile queries defined in the trigger config.

    These queries were generated by the LLM during trigger proposal
    and are specific to the discovered schema. No hardcoded SQL.
    """
    profile_data: dict = {}

    # Convert user_id for parameterized queries
    param = int(user_id) if user_id.isdigit() else user_id

    for query_def in trigger.profile_queries:
        try:
            rows = await conn.fetch(query_def.sql, param)
            profile_data[query_def.name] = [dict(r) for r in rows]
            logger.debug("Profile query '%s' returned %d rows", query_def.name, len(rows))
        except Exception as e:
            logger.warning("Profile query '%s' failed: %s", query_def.name, e)
            profile_data[query_def.name] = None

    logger.info("Built profile for user %s: %d queries executed", user_id, len(trigger.profile_queries))
    return profile_data
