"""GrowthClaw workspace management — single workspace at ~/.growthclaw/."""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

GROWTHCLAW_HOME = Path.home() / ".growthclaw"
WORKSPACE_MARKER = ".growthclaw-workspace"
TEMPLATES_DIR = Path(__file__).parent / "templates"


def get_workspace() -> Path:
    """Return the workspace path (~/.growthclaw/). Always the same location."""
    return GROWTHCLAW_HOME


def is_initialized() -> bool:
    """Check if the workspace has been initialized."""
    return (GROWTHCLAW_HOME / WORKSPACE_MARKER).exists()


def init_workspace(business_name: str = "") -> Path:
    """Initialize the GrowthClaw workspace at ~/.growthclaw/.

    Creates:
        ~/.growthclaw/
        ├── .growthclaw-workspace
        ├── .env
        ├── .gitignore
        ├── .mcp.json
        ├── .claude/settings.json
        ├── CLAUDE.md
        ├── SOUL.md
        ├── VOICE.md
        ├── OWNER.md
        ├── TOOLS.md
        ├── HEARTBEAT.md
        ├── SECURITY.md
        ├── BUSINESS.md             (placeholder — auto-generated by onboard)
        ├── skills/                 (bundled domain skills)
        │   ├── copywriter.md
        │   ├── data-analyst.md
        │   ├── experiment-scientist.md
        │   ├── email-designer.md
        │   └── growth-strategist.md
        └── data/
            ├── memory/
            └── logs/
    """
    workspace = GROWTHCLAW_HOME

    if is_initialized():
        print(f"  Workspace already exists at {workspace}")
        return workspace

    workspace.mkdir(parents=True, exist_ok=True)

    # Marker file
    (workspace / WORKSPACE_MARKER).write_text("growthclaw workspace\nversion: 0.3.0\n")

    # .env from template
    _write_env_template(workspace / ".env")

    # .gitignore
    (workspace / ".gitignore").write_text("# GrowthClaw workspace\n.env\ndata/\n*.log\n__pycache__/\n")

    # Copy all .md templates
    for md_file in TEMPLATES_DIR.glob("*.md"):
        dest = workspace / md_file.name
        content = md_file.read_text()
        # Replace placeholders in OWNER.md
        if md_file.name == "OWNER.md":
            content = (
                content.replace("{owner_name}", "")
                .replace("{owner_role}", "")
                .replace("{owner_timezone}", "")
                .replace("{preferred_channel}", "CLI")
            )
        dest.write_text(content)

    # Copy skills
    skills_dir = workspace / "skills"
    skills_dir.mkdir(exist_ok=True)
    template_skills = TEMPLATES_DIR / "skills"
    if template_skills.exists():
        for skill_file in template_skills.glob("*.md"):
            shutil.copy2(skill_file, skills_dir / skill_file.name)

    # .claude/settings.json (empty — filled by setup wizard)
    claude_dir = workspace / ".claude"
    claude_dir.mkdir(exist_ok=True)
    (claude_dir / "settings.json").write_text("{}\n")

    # .mcp.json — points to the installed growthclaw package
    python_path = shutil.which("python3") or shutil.which("python") or sys.executable
    mcp_config = {
        "mcpServers": {
            "growthclaw": {
                "command": python_path,
                "args": ["-m", "growthclaw.mcp_server"],
                "cwd": str(workspace),
            }
        }
    }
    (workspace / ".mcp.json").write_text(json.dumps(mcp_config, indent=2) + "\n")

    # Data directories
    (workspace / "data" / "memory").mkdir(parents=True, exist_ok=True)
    (workspace / "data" / "logs").mkdir(parents=True, exist_ok=True)

    return workspace


def generate_business_md(
    business_name: str,
    business_type: str,
    business_description: str,
    table_count: int,
    customer_table: str,
    customer_count: int,
    customer_id_column: str,
    funnel_stages: list[dict],
    biggest_dropoff: dict | None,
    activation_event: str,
    activation_table: str,
    activation_rate: float,
    optimal_minutes: int,
    reachability: dict | None,
    key_tables: list[str],
    triggers: list[dict],
) -> str:
    """Generate BUSINESS.md content from onboard discovery results."""
    from datetime import datetime

    lines = [
        "# Business Profile\n",
        "<!-- AUTO-GENERATED by `growthclaw onboard`. Re-run to refresh. -->\n",
        "## Overview",
        f"- **Business name**: {business_name}",
        f"- **Business type**: {business_type}",
        f"- **Description**: {business_description}",
        f"- **Discovered at**: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "## Database",
        f"- **Total tables**: {table_count}",
        f"- **Customer table**: {customer_table} ({customer_count:,} customers)",
        f"- **Customer ID column**: {customer_id_column}",
        "",
        "## Customer Funnel",
    ]

    prev_count = None
    for stage in funnel_stages:
        name = stage.get("name", "?")
        count = stage.get("count", 0)
        rate_str = ""
        if prev_count and prev_count > 0:
            rate = count / prev_count * 100
            rate_str = f" ({rate:.1f}% from previous)"
        lines.append(f"- **{name}**: {count:,}{rate_str}")
        prev_count = count

    lines.append("")

    if biggest_dropoff:
        lines.append("## Biggest Opportunity")
        lines.append(
            f"- **Drop-off**: {biggest_dropoff.get('from_stage', '?')} → {biggest_dropoff.get('to_stage', '?')}"
        )
        conv = biggest_dropoff.get("conversion_rate", 0)
        lines.append(f"- **Conversion rate**: {conv:.1%}")
        lost = biggest_dropoff.get("lost_customers", 0)
        lines.append(f"- **Lost customers**: {lost:,}")
        lines.append(f"- **Description**: {biggest_dropoff.get('description', '')}")
        lines.append("")

    lines.append("## Activation")
    lines.append(f"- **What counts**: {activation_event}")
    lines.append(f"- **Table**: {activation_table}")
    lines.append(f"- **Rate**: {activation_rate:.1f}%")
    lines.append(f"- **Optimal timing**: {optimal_minutes} minutes")
    lines.append("")

    if reachability:
        lines.append("## Reachability")
        lines.append(f"- **SMS**: {reachability.get('sms_reachable_in_dropoff', 0):,}")
        lines.append(f"- **Email**: {reachability.get('email_reachable_in_dropoff', 0):,}")
        lines.append(f"- **Push**: {reachability.get('push_reachable_in_dropoff', 0):,}")
        lines.append("")

    if key_tables:
        lines.append("## Key Tables")
        for t in key_tables:
            lines.append(f"- {t}")
        lines.append("")

    if triggers:
        lines.append("## Proposed Triggers")
        for t in triggers:
            lines.append(f"- **{t.get('name', '?')}** [{t.get('channel', 'sms').upper()}]: {t.get('description', '')}")
            lines.append(
                f"  Delay: {t.get('delay_minutes', 0)}min | Audience: ~{t.get('expected_audience_per_week', 0)}/week"
            )
        lines.append("")

    return "\n".join(lines)


def _write_env_template(path: Path) -> None:
    """Write the .env template file."""
    content = """# ═══════════════════════════════════════════════════════════════
# GrowthClaw Configuration
# ═══════════════════════════════════════════════════════════════

# ─── Database ─────────────────────────────────────────────────
CUSTOMER_DATABASE_URL=postgresql://user:password@host:5432/dbname
GROWTHCLAW_DATABASE_URL=postgresql://user:password@host:5432/dbname

# ─── LLM Provider (at least one required) ────────────────────
ANTHROPIC_API_KEY=
# NVIDIA_API_KEY=
# NVIDIA_NIM_URL=

# ─── SMS (Twilio) — optional for dry run ─────────────────────
# TWILIO_ACCOUNT_SID=
# TWILIO_AUTH_TOKEN=
# TWILIO_FROM_NUMBER=

# ─── Email — optional for dry run ────────────────────────────
GROWTHCLAW_EMAIL_PROVIDER=resend
# RESEND_API_KEY=
# GROWTHCLAW_FROM_EMAIL=
# GROWTHCLAW_FROM_NAME=

# ─── Business Context ────────────────────────────────────────
GROWTHCLAW_BUSINESS_NAME=
GROWTHCLAW_BUSINESS_DESCRIPTION=

# ─── Settings ────────────────────────────────────────────────
GROWTHCLAW_DRY_RUN=true
GROWTHCLAW_CTA_URL=https://app.example.com
GROWTHCLAW_SAMPLE_ROWS=500

# ─── Memory — optional ──────────────────────────────────────
# OPENAI_API_KEY=
"""
    path.write_text(content)
